apiVersion: v1
kind: ConfigMap
metadata:
  name: index.html
immutable: false
data:
{{ (.Files.Glob "html/*").AsConfig | indent 2 }}
  content: |
    #!/bin/bash
    echo "Hello World to Stack Overflow"'