kind: Service
apiVersion: v1
metadata:
# set your user name
  name: user12-hello-world-service
  stam: 'a'
  stam2: 5
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
# set your user name
    app: user12-hello-world
abc: 5

